{"name": "test_logins_0_failed_by_wrong_datas[data1]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '', 'passwd': 'python', 'check': '账号不能为空'}"}], "start": 1562259117924, "stop": 1562259118471, "uuid": "1600cf3f-ed9f-48bc-87e9-ca65bd8d5152", "historyId": "95a76aa0dae8e890a1e89265bf58b324", "fullName": "TestCases.test_loginpai.TestLogin#test_logins_0_failed_by_wrong_datas[data1]", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_loginpai"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-F99FSHQ"}, {"name": "thread", "value": "16424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_loginpai"}]}