{"name": "test_logins_0_failed_by_wrong_datas[data0]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '18684720553', 'passwd': '', 'check': '密码不能为空'}"}], "start": 1562259117092, "stop": 1562259117746, "uuid": "ae5cd6d0-24fd-4a97-99e8-41b92c78ba84", "historyId": "8a7d193ba520f635ee618b2c05d5824b", "fullName": "TestCases.test_loginpai.TestLogin#test_logins_0_failed_by_wrong_datas[data0]", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_loginpai"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-F99FSHQ"}, {"name": "thread", "value": "16424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_loginpai"}]}