{"name": "test_login_0_failed_by_wrong_datas[data1]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '', 'passwd': 'python', 'check': '账号不能为空'}"}], "start": 1562346500326, "stop": 1562346500582, "uuid": "583b15d3-7e37-437d-8b79-79674941b0e8", "historyId": "66cd5eefaf3924bf157c5585174a89bb", "fullName": "TestCases.test_login.TestLogin#test_login_0_failed_by_wrong_datas[data1]", "labels": [{"name": "story", "value": "登录失败"}, {"name": "feature", "value": "登录页面功能"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-F99FSHQ"}, {"name": "thread", "value": "9160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}