{"name": "test_login_0_failed_by_wrong_datas[data2]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '186847', 'passwd': 'python', 'check': '用户不存在'}"}], "start": 1562346500957, "stop": 1562346501714, "uuid": "05d97932-4485-4ac1-a185-4806095bc12c", "historyId": "d3e80c56bbf5afc6aedd05953e26ce3c", "fullName": "TestCases.test_login.TestLogin#test_login_0_failed_by_wrong_datas[data2]", "labels": [{"name": "story", "value": "登录失败"}, {"name": "feature", "value": "登录页面功能"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-F99FSHQ"}, {"name": "thread", "value": "9160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}