{"name": "test_logins_0_failed_by_wrong_datas[data3]", "status": "passed", "parameters": [{"name": "data", "value": "{'user': '18684705531', 'passwd': 'py', 'check': '请输入6-24位密码'}"}], "start": 1562259119956, "stop": 1562259120606, "uuid": "76809510-1ffd-4388-a355-707c46b0d324", "historyId": "66c49a29781fde45f1f89a8f3bf2dbe6", "fullName": "TestCases.test_loginpai.TestLogin#test_logins_0_failed_by_wrong_datas[data3]", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_loginpai"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-F99FSHQ"}, {"name": "thread", "value": "16424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_loginpai"}]}